name: 07-real-world CI

on:
  push:
    branches: [ main ]
    paths:
      - 'examples/07-real-world/**'
      - '.github/workflows/07-test.yaml'
  pull_request:
    branches: [ main ]
    paths:
      - 'examples/07-real-world/**'
      - '.github/workflows/07-test.yaml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: examples/07-real-world

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: examples/07-real-world/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linter (oxlint)
      run: npm run lint

    - name: Build TypeScript
      run: npm run build

    - name: Generate Prisma Client
      run: npm run db:generate

    - name: Run Prisma migrations
      run: npx prisma migrate deploy
      env:
        DATABASE_URL: file:./test.db

    - name: Run tests
      run: npm test
      env:
        DATABASE_URL: file:./test.db
        NODE_ENV: test

    - name: Upload coverage reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-report
        path: examples/07-real-world/coverage/